import sys
from pathlib import Path

from .config import ProjectConfig
from .util import sanitize


def _posix(p: Path | str) -> str:
    return str(p).replace('\\', '/')


def _escape_ninja(s: str) -> str:
    return s.replace('$', '$$').replace(' ', '$ ').replace(':', '$:')


def generate_ninja(config: ProjectConfig):
    """Generate build.ninja for the project."""
    ninja_path = config.working_dir / 'build.ninja'
    linker_ld = Path(__file__).parent / 'linker.ld'

    ld = _posix(config.ld_path().resolve())
    objcopy = _posix(config.objcopy_path().resolve())
    pipeline_dir = Path(__file__).parent.parent.resolve()
    python = _posix(Path(sys.executable).resolve())

    # '3dsd' is not a valid Python identifier, so the wrapper loads the
    # package via importlib instead of an import statement.
    wrapper = config.build_dir / '_3dsd_wrapper.py'
    wrapper.parent.mkdir(parents=True, exist_ok=True)
    wrapper.write_text(
        f"import sys, importlib; sys.path.insert(0, {str(pipeline_dir)!r}); "
        f"importlib.import_module('3dsd.__main__').main()\n"
    )
    tool_cmd = f'"{python}" "{_posix(wrapper.resolve())}"'

    lines = [
        '# Generated by 3dsd ninja — do not edit',
        'ninja_required_version = 1.3',
        '',
        f'ld = {ld}',
        f'objcopy = {objcopy}',
        f'tool = {tool_cmd}',
        f'linker_ld = {_posix(linker_ld.resolve())}',
        '',
        '# === Rules ===',
        '',
        'rule compile',
        '  command = $tool compile --source $in --output $out --cc $cc_path $flags_arg',
        '  description = CC $desc',
        '',
        'rule compare',
        '  command = $tool extract-compare --compiled $in --split $split --output $out --sym $sym --symbols $symbols --base-addr $base_addr --split-addr $split_addr',
        '  description = CMP $desc',
        '',
        'rule link',
        '  command = $ld $ldflags @$out.rsp -o $out -Map $out.map',
        '  rspfile = $out.rsp',
        '  rspfile_content = $in_newline',
        '  description = LINK $out',
        '',
        'rule to_binary',
        '  command = $objcopy $in -O binary $out',
        '  description = BIN $out',
        '',
        'rule recreate_cro',
        '  command = $tool recreate-cro --linked $in --original $original --output $out',
        '  description = CRO $out',
        '',
        'rule verify',
        '  command = $tool check-file --original $original --built $in',
        '  description = VERIFY $desc',
        '',
    ]

    default_targets = []
    compare_targets: list[str] = []
    ld_flags = '--entry=0 --no-warn-mismatch --use-blx -T $linker_ld'

    for bin_name, binary in config.binaries.items():
        lines.append(f'# === {bin_name} ===')
        lines.append('')

        symbols = config.symbols.get(bin_name, [])
        source_map = config.get_source_map(bin_name)
        sym_dict = {sym.addr: sym for sym in symbols if sym.addr >= 0}
        addrs = sorted(sym_dict.keys())
        bin_size = len(binary.data)
        base_addr = binary.base_addr

        sym_csv = config.working_dir / 'symbols' / f'{bin_name}.csv'
        sym_csv_posix = _posix(sym_csv)

        emitted_compile: set[str] = set()

        # Walk through all addresses to build the full object list
        link_objects: list[str] = []
        cur_addr = 0
        addr_idx = 0

        while addr_idx < len(addrs) or cur_addr < bin_size:
            if addr_idx >= len(addrs):
                sym_name = f'{cur_addr:08x}'
                sym_size = bin_size - cur_addr
                sym_addr = cur_addr
                cur_addr += sym_size
            elif cur_addr == addrs[addr_idx]:
                sym = sym_dict[cur_addr]
                sym_name = sanitize(sym.name)
                sym_size = sym.size
                sym_addr = cur_addr
                next_addr = addrs[addr_idx + 1] if addr_idx + 1 < len(addrs) else bin_size
                if cur_addr + sym_size > next_addr:
                    sym_size = next_addr - cur_addr
                cur_addr += sym_size
                addr_idx += 1
            elif cur_addr < addrs[addr_idx]:
                sym_name = f'{cur_addr:08x}'
                sym_addr = cur_addr
                cur_addr = addrs[addr_idx]
            else:
                raise RuntimeError(f"Address tracking error at {cur_addr:08x}")

            split_o = _posix(config.split_dir / bin_name / f'{sym_name}.o')

            if sym_name in source_map:
                src_path, stem = source_map[sym_name]
                build_o = _posix(config.build_dir / bin_name / f'{stem}.o')
                link_o = _posix(config.link_dir / bin_name / f'{sym_name}.o')

                if stem not in emitted_compile:
                    emitted_compile.add(stem)
                    cc_path, flags = config.get_cc(bin_name, src_path.name)
                    cc_posix = _posix(cc_path.resolve())
                    flags_arg = '--flags=' + ','.join(flags) if flags else ''

                    lines.append(f'build {_escape_ninja(build_o)}: compile {_escape_ninja(_posix(src_path))}')
                    lines.append(f'  cc_path = {cc_posix}')
                    lines.append(f'  flags_arg = {flags_arg}')
                    lines.append(f'  desc = {bin_name}/{stem}')
                    lines.append('')

                lines.append(f'build {_escape_ninja(link_o)}: compare {_escape_ninja(build_o)} | {_escape_ninja(split_o)}')
                lines.append(f'  split = {split_o}')
                lines.append(f'  sym = {sym_name}')
                lines.append(f'  symbols = {sym_csv_posix}')
                lines.append(f'  base_addr = {base_addr:#x}')
                lines.append(f'  split_addr = {sym_addr:#x}')
                lines.append(f'  desc = {bin_name}/{sym_name}')
                lines.append('')

                link_objects.append(link_o)
                compare_targets.append(link_o)
            else:
                link_objects.append(split_o)

        # Link all objects
        linked = _posix(config.out_dir / f'{bin_name}_linked')
        obj_list = ' '.join(_escape_ninja(o) for o in link_objects)
        lines.append(f'build {_escape_ninja(linked)}: link {obj_list}')
        lines.append(f'  ldflags = {ld_flags}')
        lines.append('')

        # Convert to binary
        is_cro = '.cro' in bin_name
        if is_cro:
            temp_bin = _posix(config.out_dir / f'{bin_name}.temp')
            final_bin = _posix(config.out_dir / bin_name)
            orig_bin = _posix(next(p for p in config.originals if p.name == bin_name))

            lines.append(f'build {_escape_ninja(temp_bin)}: to_binary {_escape_ninja(linked)}')
            lines.append('')

            lines.append(f'build {_escape_ninja(final_bin)}: recreate_cro {_escape_ninja(temp_bin)}')
            lines.append(f'  original = {orig_bin}')
            lines.append('')
        else:
            final_bin = _posix(config.out_dir / bin_name)
            lines.append(f'build {_escape_ninja(final_bin)}: to_binary {_escape_ninja(linked)}')
            lines.append('')

        # Verify
        orig_file = next((p for p in config.originals if p.name == bin_name), None)
        if orig_file:
            stamp = _posix(config.out_dir / f'{bin_name}.verified')
            lines.append(f'build {_escape_ninja(stamp)}: verify {_escape_ninja(final_bin)}')
            lines.append(f'  original = {_posix(orig_file)}')
            lines.append(f'  desc = {bin_name}')
            lines.append('')

        default_targets.append(final_bin)

    # Phony targets
    if compare_targets:
        lines.append(f'build compile: phony {" ".join(_escape_ninja(t) for t in compare_targets)}')
        lines.append('')

    if default_targets:
        lines.append(f'default {" ".join(_escape_ninja(t) for t in default_targets)}')
        lines.append('')

    ninja_path.write_text('\n'.join(lines))
    print(f"Generated {ninja_path}")
    print(f"  Run 'ninja' to build, or 'ninja compile' to compile only.")
